apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "subnet-manager.fullname" . }}
  labels:
    {{- include "subnet-manager.labels" . | nindent 4 }}
data:
  {{- range $key, $value := merge (deepCopy .Values.extraConfig) .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
